# Generated by Django 4.1.2 on 2023-01-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cart_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
    ]
